/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-27 18:50:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("	.bttnStyle\n");
      out.write("	{\n");
      out.write("		background-color: lightblue;\n");
      out.write("		border-radius: 0.50rem;\n");
      out.write("		border:1px solid transperent;\n");
      out.write("	}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	var xhttp=new XMLHttpRequest();\n");
      out.write("	var RazorpayOrderId;\n");
      out.write("	function CreateOrderID()\n");
      out.write("	{\n");
      out.write("		/*  alert(\"1\");  */\n");
      out.write("		var number=document.getElementById(\"amount\").value;\n");
      out.write("		xhttp.open(\"GET\",\"http://localhost:8080/Project/OrderCreation?amount=\"+number,false);\n");
      out.write("		/* alert(\"2\"); */\n");
      out.write("		xhttp.send();\n");
      out.write("		RazorpayOrderId=xhttp.responseText;\n");
      out.write("		  \n");
      out.write("		alert(number);  \n");
      out.write("		OpenCheckOut(number); \n");
      out.write("		OpenCheckOut();\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("<script src=\"https://checkout.razorpay.com/v1/checkout.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	function OpenCheckOut()\n");
      out.write("	{\n");
      out.write("		/* alert(\"3\");  */\n");
      out.write("		var number=document.getElementById(\"amount\").value;\n");
      out.write("		/* alert(number); */\n");
      out.write("		var options={\n");
      out.write("				\"key\":\"rzp_test_sPIH2pgpcqCtml\",\n");
      out.write("				\"amount\":number,\n");
      out.write("				\"currency\":\"INR\",\n");
      out.write("				\"name\":\"Villince\",	\n");
      out.write("				\"description\":\"Test\",\n");
      out.write("				\"order_id\":RazorpayOrderId,\n");
      out.write("				\n");
      out.write("				\"callback_url\":\"http://localhost:8080/Project/customer-home.jsp\",\n");
      out.write("				\"prefill\":{\n");
      out.write("					\"name\":\"Villince Patel\",\n");
      out.write("					\"email\":\"vilincep@gmail.com\",\n");
      out.write("					\"contact\":\"9638998288\"\n");
      out.write("				},\n");
      out.write("				\"notes\":{\n");
      out.write("					\"address\":\"Ahmedabad\"\n");
      out.write("				},\n");
      out.write("				\"theme\":{\n");
      out.write("					\"color\":\"#3399cc\"\n");
      out.write("				}\n");
      out.write("				\n");
      out.write("				\n");
      out.write("		};\n");
      out.write("		var rzp1=new Razorpay(options);\n");
      out.write("		rzp1.on('payment.failed',function (response){\n");
      out.write("			alert(response.error.code);\n");
      out.write("	        alert(response.error.description);\n");
      out.write("	        alert(response.error.source);\n");
      out.write("	        alert(response.error.step);\n");
      out.write("	        alert(response.error.reason);\n");
      out.write("	        alert(response.error.metadata.order_id);\n");
      out.write("	        alert(response.error.metadata.payment_id);\n");
      out.write("		});\n");
      out.write("		rzp1.open();\n");
      out.write("	    /* e.preventDefault(); */\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"order_id\">\n");
      out.write("	\n");
      out.write("</div>\n");
int am = Integer.parseInt(request.getParameter("amount")); 
      out.write("\n");
      out.write("<center> \n");
      out.write("	<input type=\"hidden\" id=\"amount\" value=\"");
      out.print(am);
      out.write("\">\n");
      out.write("	\n");
      out.write("	<button id=\"payButton\" onclick=\"CreateOrderID()\" class=\"bttnStyle\">Pay Now</button>\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
