/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-27 18:29:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class seller_002dverify_002dotp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!--A Design by W3layouts\n");
      out.write("   Author: W3layout\n");
      out.write("   Author URL: http://w3layouts.com\n");
      out.write("   License: Creative Commons Attribution 3.0 Unported\n");
      out.write("   License URL: http://creativecommons.org/licenses/by/3.0/\n");
      out.write("   -->\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"zxx\">\n");
      out.write("   <head>\n");
      out.write("      <title>Toys Shop an Ecommerce Category Bootstrap Responsive Web Template | Home :: w3layouts</title>\n");
      out.write("      <!--meta tags -->\n");
      out.write("      <meta charset=\"UTF-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("      <meta name=\"keywords\" content=\"Toys Shop Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \n");
      out.write("         Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\n");
      out.write("      <script>\n");
      out.write("         addEventListener(\"load\", function () {\n");
      out.write("         	setTimeout(hideURLbar, 0);\n");
      out.write("         }, false);\n");
      out.write("         \n");
      out.write("         function hideURLbar() {\n");
      out.write("         	window.scrollTo(0, 1);\n");
      out.write("         }\n");
      out.write("      </script>\n");
      out.write("      <!--//meta tags ends here-->\n");
      out.write("      <!--booststrap-->\n");
      out.write("      <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n");
      out.write("      <!--//booststrap end-->\n");
      out.write("      <!-- font-awesome icons -->\n");
      out.write("      <link href=\"css/fontawesome-all.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\">\n");
      out.write("      <!-- //font-awesome icons -->\n");
      out.write("      <!--Shoping cart-->\n");
      out.write("      <link rel=\"stylesheet\" href=\"css/shop.css\" type=\"text/css\" />\n");
      out.write("      <!--//Shoping cart-->\n");
      out.write("      <!--stylesheets-->\n");
      out.write("      <link href=\"css/style.css\" rel='stylesheet' type='text/css' media=\"all\">\n");
      out.write("      <!--//stylesheets-->\n");
      out.write("      <link href=\"//fonts.googleapis.com/css?family=Sunflower:500,700\" rel=\"stylesheet\">\n");
      out.write("      <link href=\"//fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\n");
      out.write("   </head>\n");
      out.write("   <body>\n");
      out.write("      <!--headder-->\n");
      out.write("<div class=\"header-outs\" id=\"home\">\n");
      out.write("		<div class=\"header-bar\">\n");
      out.write("			<div class=\"info-top-grid\">\n");
      out.write("				<div class=\"info-contact-agile\">\n");
      out.write("					<ul>\n");
      out.write("						<li><span class=\"fas fa-phone-volume\"></span>\n");
      out.write("							<p>+91 8200405262</p></li>\n");
      out.write("						<li><span class=\"fas fa-envelope\"></span>\n");
      out.write("							<p>\n");
      out.write("								<a href=\"khajinastore723@gmail.com\n");
      out.write("                        \">khajinastore723@gmail.com</a>\n");
      out.write("							</p></li>\n");
      out.write("						<li></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"container-fluid\">\n");
      out.write("				<div class=\"hedder-up row\">\n");
      out.write("					<div class=\"col-lg-3 col-md-3 logo-head\">\n");
      out.write("						<h1>\n");
      out.write("							<a class=\"navbar-brand\" href=\"index.html\">Khajina-Shopping</a>\n");
      out.write("						</h1>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-lg-5 col-md-6 search-right\">\n");
      out.write("						<form class=\"form-inline my-lg-0\">\n");
      out.write("							<input class=\"form-control mr-sm-2\" type=\"search\"\n");
      out.write("								placeholder=\"Search\">\n");
      out.write("							<button class=\"btn\" type=\"submit\">Search</button>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"col-lg-4 col-md-3 right-side-cart\">\n");
      out.write("						<div class=\"cart-icons\">\n");
      out.write("							<ul>\n");
      out.write("								<li><span class=\"far fa-heart\"></span></li>\n");
      out.write("								<li>\n");
      out.write("									<button type=\"button\" data-toggle=\"modal\"\n");
      out.write("										data-target=\"#exampleModal\">\n");
      out.write("										<span class=\"far fa-user\"></span>\n");
      out.write("									</button>\n");
      out.write("								</li>\n");
      out.write("								<li class=\"toyscart toyscart2 cart cart box_1\">\n");
      out.write("									<form action=\"#\" method=\"post\" class=\"last\">\n");
      out.write("										<input type=\"hidden\" name=\"cmd\" value=\"_cart\"> <input\n");
      out.write("											type=\"hidden\" name=\"display\" value=\"1\">\n");
      out.write("										<button class=\"top_toys_cart\" type=\"submit\" name=\"submit\"\n");
      out.write("											value=\"\">\n");
      out.write("											<span class=\"fas fa-cart-arrow-down\"></span>\n");
      out.write("										</button>\n");
      out.write("									</form>\n");
      out.write("								</li>\n");
      out.write("							</ul>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("         <nav class=\"navbar navbar-expand-lg navbar-light\">\n");
      out.write("               <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("               <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("               </button>\n");
      out.write("               <div class=\"collapse navbar-collapse justify-content-center\" id=\"navbarSupportedContent\">\n");
      out.write("                  <ul class=\"navbar-nav \">\n");
      out.write("                     <li class=\"nav-item active\">\n");
      out.write("                        <a class=\"nav-link\" href=\"index.html\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("                     </li>\n");
      out.write("                   <li class=\"nav-item dropdown\">\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                        Register\n");
      out.write("                        </a>\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("                           <a class=\"nav-link\" href=\"seller-register.jsp\">As Seller</a>\n");
      out.write("                           <a class=\"nav-link \" href=\"customer-register.jsp\">As Customer</a>\n");
      out.write("                        </div>\n");
      out.write("                     </li>\n");
      out.write("                     <li class=\"nav-item dropdown\">\n");
      out.write("                        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown1\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                        Login\n");
      out.write("                        </a>\n");
      out.write("                        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("                           <a class=\"nav-link\" href=\"seller-login.jsp\">Seller</a>\n");
      out.write("                           <a class=\"nav-link \" href=\"customer-login.jsp\">Customer</a>\n");
      out.write("                           <a class=\"nav-link \" href=\"admin-login.jsp\">Admin</a>\n");
      out.write("                        </div>\n");
      out.write("                     </li>\n");
      out.write("                    \n");
      out.write("                  </ul>\n");
      out.write("               </div>\n");
      out.write("            </nav>\n");
      out.write("      </div>\n");
      out.write("	  </div>\n");
      out.write("      <!--//headder-->\n");
      out.write("      <!-- banner -->\n");
      out.write("      <div class=\"inner_page-banner one-img\">\n");
      out.write("      </div>\n");
      out.write("      <!--//banner -->\n");
      out.write("      <!-- short -->\n");
      out.write("      <div class=\"using-border py-3\">\n");
      out.write("         <div class=\"inner_breadcrumb  ml-4\">\n");
      out.write("            <ul class=\"short_ls\">\n");
      out.write("               <li>\n");
      out.write("                  <a href=\"index.html\">Home</a>\n");
      out.write("                  <span>/ /</span>\n");
      out.write("               </li>\n");
      out.write("               <li>Verify OTP</li>\n");
      out.write("            </ul>\n");
      out.write("         </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- //short-->\n");
      out.write("      <!--contact -->\n");
      out.write("      <section class=\"contact py-lg-4 py-md-3 py-sm-3 py-3\">\n");
      out.write("         <div class=\"container py-lg-5 py-md-4 py-sm-4 py-3\">\n");
      out.write("            <h3 class=\"title text-center mb-lg-5 mb-md-4 mb-sm-4 mb-3\">Verify OTP</h3>\n");
      out.write("            <div class=\"contact-list-grid\">\n");
      out.write("            ");
 String msg = (String)request.getAttribute("msg");
      out.write("\n");
      out.write("            ");
if(msg!=null){ 
      out.write("\n");
      out.write("            	<h3>");
out.print(msg); 
      out.write("</h3>\n");
      out.write("            ");
} 
      out.write("\n");
      out.write("               <form action=\"SellerController\" method=\"post\">\n");
      out.write("                  <div class=\" agile-wls-contact-mid\">\n");
      out.write("                     <div class=\"form-group contact-forms\">\n");
      out.write("                     	");
String email = (String)request.getAttribute("email"); 
      out.write("\n");
      out.write("                     	");
int otp = (Integer)request.getAttribute("otp"); 
      out.write("\n");
      out.write("                        <input type=\"hidden\" name=\"email\" value=\"");
      out.print(email);
      out.write("\">\n");
      out.write("                        <input type=\"hidden\" name=\"otp1\" value=\"");
      out.print(otp);
      out.write("\">\n");
      out.write("                        <input type=\"text\" class=\"form-control\" name=\"otp2\" placeholder=\"Enter OTP\">\n");
      out.write("                     </div>\n");
      out.write("                     <button type=\"submit\" name=\"action\" value=\"verify\" class=\"btn btn-block sent-butnn\">Verify OTP</button>\n");
      out.write("                  </div>\n");
      out.write("               </form>\n");
      out.write("            </div>\n");
      out.write("         </div>\n");
      out.write("         <!--//contact-map -->\n");
      out.write("      </section>\n");
      out.write("      <!--subscribe-address-->\n");
      out.write(" 	<section class=\"subscribe\">\n");
      out.write("		<div class=\"container-fluid\">\n");
      out.write("			<div class=\"row\">\n");
      out.write("				<div class=\"col-lg-6 col-md-6 map-info-right px-0\">\n");
      out.write("					<iframe\n");
      out.write("						src=\"https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3150859.767904157!2d-96.62081048651531!3d39.536794757966845!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1408111832978\">\n");
      out.write("					</iframe>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"col-lg-6 col-md-6 address-w3l-right text-center\">\n");
      out.write("					<div class=\"address-gried \">\n");
      out.write("						<span class=\"far fa-map\"></span>\n");
      out.write("						<p>\n");
      out.write("							212,Toys Shop Road<br> Teen Darwaja,Ahmedabad\n");
      out.write("						<p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"address-gried mt-3\">\n");
      out.write("						<span class=\"fas fa-phone-volume\"></span>\n");
      out.write("						<p>\n");
      out.write("							(+91)8200405262<br>(+91)8200405262\n");
      out.write("						</p>\n");
      out.write("					</div>\n");
      out.write("					<div class=\" address-gried mt-3\">\n");
      out.write("						<span class=\"far fa-envelope\"></span>\n");
      out.write("						<p>\n");
      out.write("							<a href=\"khajinastore723@gmail.com\">khajinastore723@gmail.com</a> <br>\n");
      out.write("							<a href=\"khajinastore723@gmail.com\">khajinastore723@gmail.com</a>\n");
      out.write("						</p>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<!--//subscribe-address-->\n");
      out.write("	<section class=\"sub-below-address py-lg-4 py-md-3 py-sm-3 py-3\">\n");
      out.write("		<div class=\"container py-lg-5 py-md-5 py-sm-4 py-3\">\n");
      out.write("			<h3 class=\"title clr text-center mb-lg-5 mb-md-4 mb-sm-4 mb-3\">Get\n");
      out.write("				In Touch Us</h3>\n");
      out.write("			<div class=\"icons mt-4 text-center\">\n");
      out.write("				<ul>\n");
      out.write("					<li><a href=\"#\"><span class=\"fab fa-facebook-f\"></span></a></li>\n");
      out.write("					<li><a href=\"#\"><span class=\"fas fa-envelope\"></span></a></li>\n");
      out.write("					<li><a href=\"#\"><span class=\"fas fa-rss\"></span></a></li>\n");
      out.write("					<li><a href=\"#\"><span class=\"fab fa-vk\"></span></a></li>\n");
      out.write("				</ul>\n");
      out.write("				<p class=\"my-3\">You can subscribe our newsletter, which bring all the new update or when we have the latest new toys and product </p>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"email-sub-agile\">\n");
      out.write("				<form action=\"#\" method=\"post\">\n");
      out.write("					<div class=\"form-group sub-info-mail\">\n");
      out.write("						<input type=\"email\" class=\"form-control email-sub-agile\"\n");
      out.write("							placeholder=\"Email\">\n");
      out.write("					</div>\n");
      out.write("					<div class=\"text-center\">\n");
      out.write("						<button type=\"submit\" class=\"btn subscrib-btnn\">Subscribe</button>\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<!--//subscribe-->\n");
      out.write("	<!-- footer -->\n");
      out.write("	<footer class=\"py-lg-4 py-md-3 py-sm-3 py-3 text-center\">\n");
      out.write("		<div class=\"copy-agile-right\">\n");
      out.write("			<p>\n");
      out.write("				© 2023 Khajina-Shopping. All Rights Reserved | Design by <a\n");
      out.write("					href=\"http://localhost:8080/Khajina_Shopping\" target=\"_blank\">Khajina Shopping</a>\n");
      out.write("			</p>\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("	<!-- //footer -->\n");
      out.write("	<!-- Modal 1-->\n");
      out.write("	<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("		aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\" role=\"document\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-header\">\n");
      out.write("					<h5 class=\"modal-title\" id=\"exampleModalLabel\">Login</h5>\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\">\n");
      out.write("						<span aria-hidden=\"true\">&times;</span>\n");
      out.write("					</button>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-body\">\n");
      out.write("					<div class=\"register-form\">\n");
      out.write("						<form action=\"#\" method=\"post\">\n");
      out.write("							<div class=\"fields-grid\">\n");
      out.write("								<div class=\"styled-input\">\n");
      out.write("									<input type=\"text\" placeholder=\"Your Name\" name=\"Your Name\"\n");
      out.write("										required=\"\">\n");
      out.write("								</div>\n");
      out.write("								<div class=\"styled-input\">\n");
      out.write("									<input type=\"email\" placeholder=\"Your Email\" name=\"Your Email\"\n");
      out.write("										required=\"\">\n");
      out.write("								</div>\n");
      out.write("								<div class=\"styled-input\">\n");
      out.write("									<input type=\"password\" placeholder=\"password\" name=\"password\"\n");
      out.write("										required=\"\">\n");
      out.write("								</div>\n");
      out.write("								<button type=\"submit\" class=\"btn subscrib-btnn\">Login</button>\n");
      out.write("							</div>\n");
      out.write("						</form>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"modal-footer\">\n");
      out.write("					<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("						data-dismiss=\"modal\">Close</button>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- //Modal 1-->\n");
      out.write("	<!--js working-->\n");
      out.write("	<script src='js/jquery-2.2.3.min.js'></script>\n");
      out.write("	<!--//js working-->\n");
      out.write("	<!-- cart-js -->\n");
      out.write("	<script src=\"js/minicart.js\"></script>\n");
      out.write("	<script>\n");
      out.write("		toys.render();\n");
      out.write("\n");
      out.write("		toys.cart.on('toys_checkout', function(evt) {\n");
      out.write("			var items, len, i;\n");
      out.write("\n");
      out.write("			if (this.subtotal() > 0) {\n");
      out.write("				items = this.items();\n");
      out.write("\n");
      out.write("				for (i = 0, len = items.length; i < len; i++) {\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("	<!-- //cart-js -->\n");
      out.write("	<!--responsiveslides banner-->\n");
      out.write("	<script src=\"js/responsiveslides.min.js\"></script>\n");
      out.write("	<script>\n");
      out.write("		// You can also use \"$(window).load(function() {\"\n");
      out.write("		$(function() {\n");
      out.write("			// Slideshow 4\n");
      out.write("			$(\"#slider4\").responsiveSlides({\n");
      out.write("				auto : true,\n");
      out.write("				pager : false,\n");
      out.write("				nav : true,\n");
      out.write("				speed : 900,\n");
      out.write("				namespace : \"callbacks\",\n");
      out.write("				before : function() {\n");
      out.write("					$('.events').append(\"<li>before event fired.</li>\");\n");
      out.write("				},\n");
      out.write("				after : function() {\n");
      out.write("					$('.events').append(\"<li>after event fired.</li>\");\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("	<!--// responsiveslides banner-->\n");
      out.write("	<!--slider flexisel -->\n");
      out.write("	<script src=\"js/jquery.flexisel.js\"></script>\n");
      out.write("	<script>\n");
      out.write("		$(window).load(function() {\n");
      out.write("			$(\"#flexiselDemo1\").flexisel({\n");
      out.write("				visibleItems : 3,\n");
      out.write("				animationSpeed : 3000,\n");
      out.write("				autoPlay : true,\n");
      out.write("				autoPlaySpeed : 2000,\n");
      out.write("				pauseOnHover : true,\n");
      out.write("				enableResponsiveBreakpoints : true,\n");
      out.write("				responsiveBreakpoints : {\n");
      out.write("					portrait : {\n");
      out.write("						changePoint : 480,\n");
      out.write("						visibleItems : 1\n");
      out.write("					},\n");
      out.write("					landscape : {\n");
      out.write("						changePoint : 640,\n");
      out.write("						visibleItems : 2\n");
      out.write("					},\n");
      out.write("					tablet : {\n");
      out.write("						changePoint : 768,\n");
      out.write("						visibleItems : 2\n");
      out.write("					}\n");
      out.write("				}\n");
      out.write("			});\n");
      out.write("\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("	<!-- //slider flexisel -->\n");
      out.write("	<!-- start-smoth-scrolling -->\n");
      out.write("	<script src=\"js/move-top.js\"></script>\n");
      out.write("	<script src=\"js/easing.js\"></script>\n");
      out.write("	<script>\n");
      out.write("		jQuery(document).ready(function($) {\n");
      out.write("			$(\".scroll\").click(function(event) {\n");
      out.write("				event.preventDefault();\n");
      out.write("				$('html,body').animate({\n");
      out.write("					scrollTop : $(this.hash).offset().top\n");
      out.write("				}, 900);\n");
      out.write("			});\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("	<!-- start-smoth-scrolling -->\n");
      out.write("	<!-- here stars scrolling icon -->\n");
      out.write("	<script>\n");
      out.write("		$(document).ready(function() {\n");
      out.write("\n");
      out.write("			var defaults = {\n");
      out.write("				containerID : 'toTop', // fading element id\n");
      out.write("				containerHoverID : 'toTopHover', // fading element hover id\n");
      out.write("				scrollSpeed : 1200,\n");
      out.write("				easingType : 'linear'\n");
      out.write("			};\n");
      out.write("			$().UItoTop({\n");
      out.write("				easingType : 'easeOutQuart'\n");
      out.write("			});\n");
      out.write("\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("	<!-- //here ends scrolling icon -->\n");
      out.write("	<!--bootstrap working-->\n");
      out.write("	<script src=\"js/bootstrap.min.js\"></script>\n");
      out.write("	<!-- //bootstrap working-->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
